<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin_flyers_model extends CI_Model
{

    public $table = 'tbl_flyer_detail';
    public $id = 'pk_flyer_detail_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    //get all user flyers
    public function get_user_flyer(){
        //$this->db->where('repeater',0);
        $this->db->order_by('uFlyerId','DESC');
        return $this->db->get('user_flyers')->result();

    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->join('tbl_flyer_size','tbl_flyer_size.pk_flyer_size_id=tbl_flyer_detail.flyer_image_size');
        $this->db->join('tbl_admin','tbl_admin.admin_id=tbl_flyer_detail.admin_id');
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('pk_flyer_detail_id', $q);
	$this->db->or_like('flyer_title', $q);
	$this->db->or_like('flyer_image', $q);
	$this->db->or_like('flyer_image_size', $q);
	$this->db->or_like('flyer_created_image', $q);
	$this->db->or_like('flyer_json_file', $q);
	$this->db->or_like('flyer_status', $q);
	$this->db->or_like('flyer_approved', $q);
	$this->db->or_like('flyer_approved_by', $q);
	$this->db->or_like('flyer_creation_date', $q);
	$this->db->or_like('admin_id', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('pk_flyer_detail_id', $q);
	$this->db->or_like('flyer_title', $q);
	$this->db->or_like('flyer_image', $q);
	$this->db->or_like('flyer_image_size', $q);
	$this->db->or_like('flyer_created_image', $q);
	$this->db->or_like('flyer_json_file', $q);
	$this->db->or_like('flyer_status', $q);
	$this->db->or_like('flyer_approved', $q);
	$this->db->or_like('flyer_approved_by', $q);
	$this->db->or_like('flyer_creation_date', $q);
	$this->db->or_like('admin_id', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
        $this->db->query("DELETE FROM tbl_flyer_properties where  pk_flyer_id = " . $id);
        $this->db->query("DELETE FROM tbl_flyer_color_set where  pk_flyer_id = " . $id);
    }



}

/* End of file Admin_flyers_model.php */
/* Location: ./application/models/Admin_flyers_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-20 01:34:11 */
/* http://harviacode.com */