<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin_activity_model extends CI_Model
{

    public $table = 'admin_activity';
    public $id = 'activity_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($limit=9)
    {
        $this->db->order_by($this->id, $this->order);
        if($limit!==9){
            $this->db->limit($limit);
        }

        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_all_by_admin($admin_id){
        $this->db->order_by($this->id, $this->order);
        $this->db->where('admin_id', $admin_id);
        return $this->db->get($this->table)->result();
    }

    function get_by_filter($activity_type, $admin_id=NULL){
        $this->db->order_by($this->id, $this->order);
        if($admin_id!== NULL){
            $this->db->where('admin_id', $admin_id);
        }

        if($activity_type!== NULL){
            $this->db->where('activity_type', $activity_type);
        }

        return $this->db->get($this->table)->result();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('activity_id', $q);
	$this->db->or_like('action_type', $q);
	$this->db->or_like('activity_text', $q);
	$this->db->or_like('activity_date', $q);
	$this->db->or_like('admin_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('activity_id', $q);
	$this->db->or_like('action_type', $q);
	$this->db->or_like('activity_text', $q);
	$this->db->or_like('activity_date', $q);
	$this->db->or_like('admin_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Admin_activity_model.php */
/* Location: ./application/models/Admin_activity_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-06 02:05:16 */
/* http://harviacode.com */