<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin_coupons_model extends CI_Model
{

    public $table = 'admi_coupons';
    public $id = 'coupon_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
     // get coupin uses info
    function get_coupin_use($code)
    {
        $query="SELECT (select count(used_id) FROM admi_coupons_used where coupon_code='".$code."' ) as total,acu.* 
        FROM admi_coupons_used as acu 
        WHERE acu.coupon_code='".$code."'";
        $queryRS = $this->db->query($query);
        if ($queryRS->num_rows() > 0) {
            return $queryRS->result_array();
        } else {
            return false;
        }
    }
    // get total rows
    function total_rows($q = NULL, $records = NULL) {
        $this->db->like('coupon_id', $q, $records);
    	$this->db->or_like('coupon_title', $q, $records);
    	$this->db->or_like('coupon_description', $q, $records);
    	$this->db->or_like('coupon_start_date', $q, $records);
    	$this->db->or_like('coupone_end_date', $q, $records);
    	$this->db->or_like('coupon_type', $q, $records);
    	$this->db->or_like('coupon_value', $q, $records);
    	$this->db->or_like('coupon_maximum_uses', $q, $records);
    	$this->db->or_like('coupon_apply_once', $q, $records);
    	$this->db->or_like('coupon_new_signups', $q, $records);
    	$this->db->or_like('coupon_apply_on_existing_client_only', $q, $records);
    	$this->db->or_like('coupon_date', $q, $records);
    	$this->db->or_like('coupon_modified_date', $q, $records);
    	$this->db->or_like('coupon_modified_admin', $q, $records);
    	$this->db->or_like('admin_id', $q, $records);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $records = NULL) {
        $this->db->select('*,(select count(used_id) FROM admi_coupons_used where coupon_code='.$this->table.'.coupon_code) as total');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('coupon_id', $q, $records);
    	$this->db->or_like('coupon_title', $q, $records);
    	$this->db->or_like('coupon_description', $q, $records);
    	$this->db->or_like('coupon_start_date', $q, $records);
    	$this->db->or_like('coupone_end_date', $q, $records);
    	$this->db->or_like('coupon_type', $q, $records);
    	$this->db->or_like('coupon_value', $q, $records);
    	$this->db->or_like('coupon_maximum_uses', $q, $records);
    	$this->db->or_like('coupon_apply_once', $q, $records);
    	$this->db->or_like('coupon_new_signups', $q, $records);
    	$this->db->or_like('coupon_apply_on_existing_client_only', $q, $records);
    	$this->db->or_like('coupon_date', $q, $records);
    	$this->db->or_like('coupon_modified_date', $q, $records);
    	$this->db->or_like('coupon_modified_admin', $q, $records);
    	$this->db->or_like('admin_id', $q, $records);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function check_coupons_code($code){
       // $query = 'select * from admi_coupons where coupon_code = "'. $code . '"';
        $this->db->select('*');
        $this->db->from('admi_coupons');
        $this->db->where('coupon_code', $code);
        $query = $this->db->get();
        return $query->result();
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Admin_coupons_model.php */
/* Location: ./application/models/Admin_coupons_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-08 11:05:00 */
/* http://harviacode.com */