<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Flyer_size_model extends CI_Model
{

    public $table = 'tbl_flyer_size';
    public $id = 'pk_flyer_size_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('pk_flyer_size_id', $q);
	$this->db->or_like('flyer_size_title', $q);
	$this->db->or_like('flyer_size_width', $q);
	$this->db->or_like('flyer_size_height', $q);
	$this->db->or_like('flyer_size_status', $q);
	$this->db->or_like('flyer_size_date', $q);
	$this->db->or_like('modifiedDate', $q);
	$this->db->or_like('adminId', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('pk_flyer_size_id', $q);
	$this->db->or_like('flyer_size_title', $q);
	$this->db->or_like('flyer_size_width', $q);
	$this->db->or_like('flyer_size_height', $q);
	$this->db->or_like('flyer_size_status', $q);
	$this->db->or_like('flyer_size_date', $q);
	$this->db->or_like('modifiedDate', $q);
	$this->db->or_like('adminId', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Flyer_size_model.php */
/* Location: ./application/models/Flyer_size_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-05 22:05:03 */
/* http://harviacode.com */