<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Subscriber_model extends CI_Model
{

    public $table = 'tbl_subscriber';
    public $id = 'subId';
    public $order = 'DESC';
   
    function __construct()
    {
        parent::__construct();
        $this->load->model('frontend/commonmodel');
        $this->load->library('form_validation');
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
		return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
	
	 function get_record($email)
    {
        $this->db->where('subEmail', $email);
       return $this->db->get($this->table)->row();
    
	}
	
	 function insert_history($data)
    {
       $this->db->insert('subscriber_login_history', $data);
       return true;
    
	}
	
	 function newsletter_record($email)
    {
        $this->db->where('email', $email);
       return $this->db->get('tbl_newsletter_subs')->row();
    
	}
	 
	function insert_newsletter($data){
		$this->db->insert('tbl_newsletter_subs', $data);
		return $this->db->insert_id();
	}
	
	 // update data
    function update_newsletter($id, $data)
    {
        $this->db->where('id', $id);
        $this->db->update('tbl_newsletter_subs', $data);
    }
}

/* End of file Users_model.php */
/* Location: ./application/models/Users_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-29 14:59:51 */
/* http://harviacode.com */